[E 2025-10-19 22:06:51,301 D:\Miniconda3\Lib\site-packages\shioaji\utils.py:49:raise_resp_error] {'status': {'status_code': 400}, 'response': {'token': '', 'accounts': [], 'detail': 'key: GhUt4hr1n9AT7rxfbmpz7SXjuggfHJkdjc8Pw8pdx5R2 not match signature.', 'ip_address': '124.218.23.111', 'person_id': 'F125111804', 'client_name': '', 'contract_download': False, 'web_token': '', 'solace_props': None}}
